### ISSUE TITLE
Cannot compile the source code Android studio 1.1.0 && I would like to use some code for SPP-R300

### ISSUE THREAD

**Issue by sarperonal** [rocboronat/FewlapsLovesBixolon#2]
Dear Fewlaps Team,

I am trying to develop an app for myself and I am stock on Android Bluetooth connection between Bixolon Spp-R300. 

I have try your code from git hub but it was for 2'' model, I am not able to compile it anyway. I have faced with some gradle script problem. 

After File-> Import Project I have "Message Gradle Sync" says that Failed to sync Gradle project

The project using an unsopported version of the Android Gradle Plugin 0.12.2 the recommend version is 1.1.0 || Fix plugin version and re-import project.

After clicking Fix plugin button I have another message The project may be using a version of Gradle that does not contain the method "runProguard()"

What ever I try I couldnt solve problems. 

Could you please support me in this issue? 

Best Regards.

**Comment by rocboronat** [comment]
Hi!

I'll make it work with the last AS :·)

By the way, the code is tested with the SPP-R200IIBK and the SPP-R300WK printers. There's only one difference: the number of characters that it can print in one line. The first line of PrintingActivity.java has a constant for the 200 printer, and another (an commented) one for the 300. Comment the 200 one and uncomment the 300 one, and that's all.

Thanks for the issue, @sarperonal !

**Comment by sarperonal** [comment]
Hi Roc!

I see the commented line and verry happy that I can use the code for R300  

Kindly waiting for the replay 

Thank you for the solution. @rocboronat

**Comment by sarperonal** [comment]
Hi!
How is it going? Do you able to get it work with android 4.2  or 4.4? 
Waiting good news from you :)
Best regards.

**Comment by rocboronat** [comment]
Yep! Yes, it works with Android 4.4 for sure (it was tested on a real device).

The issue is related with the last version of Android Studio, not with Android itself.

By the way, I didn't do it. Of course, don't hesitate of forking the project, fixing it, and making a Pull Request if you have time... :·)
